// scripts/coverage-report.mjs — regenerate _reports/STATE-FRAME-COVERAGE.md.
import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const framesDir = join(here, '..', 'frames');
const reportsDir = join(here, '..', '_reports');
mkdirSync(reportsDir, { recursive: true });

const rows = [];
for (const f of readdirSync(framesDir).filter(x => x.endsWith('.json'))) {
  const j = JSON.parse(readFileSync(join(framesDir, f), 'utf8'));
  rows.push({
    state: j.state, type: j.application_type, burden: j.burden,
    cites: (j.governing_authority || []).length,
    status: j.state === 'GENERIC' ? 'GENERIC' : (j.validation_status || 'verified'),
    file: f,
  });
}
// GENERIC + flagged first, then alpha
const rank = (r) => r.status === 'GENERIC' ? 0 : r.status === 'flagged' ? 1 : 2;
rows.sort((a, b) => rank(a) - rank(b) || a.state.localeCompare(b.state) || a.type.localeCompare(b.type));

const shifts = rows.filter(r => r.burden === 'prima_facie_shifting');
const juris = new Set(rows.filter(r => r.state !== 'GENERIC').map(r => r.state));

let md = `# ZoningFight — State Frame Coverage\n\n`;
md += `Generated by scripts/coverage-report.mjs. Branch: state-frame-backfill.\n\n`;
md += `- Jurisdictions with frames: **${juris.size}** (target 50 + FL)\n`;
md += `- Total frame files: **${rows.filter(r => r.state !== 'GENERIC').length}**\n`;
md += `- Burden-shift (prima_facie_shifting) frames: **${shifts.length}** ${shifts.length ? '→ ' + shifts.map(s => s.state + '/' + s.type).join(', ') : '(FL only lives in the frozen file; none added)'}\n`;
md += `- Flagged: **${rows.filter(r => r.status === 'flagged').length}**\n\n`;
md += `Every prima_facie_shifting frame must carry ≥1 verified citation. A frame with zero citations is acceptable and expected for most jurisdictions (§0 understatement).\n\n`;
md += `| State | Type | Burden | Cites | Status |\n|---|---|---|---:|---|\n`;
for (const r of rows) md += `| ${r.state} | ${r.type} | ${r.burden} | ${r.cites} | ${r.status} |\n`;

writeFileSync(join(reportsDir, 'STATE-FRAME-COVERAGE.md'), md);
console.log(`coverage report: ${juris.size} jurisdictions, ${rows.length} frame files`);
